### ISSUE TITLE
Matlab codes about nested Krylov methods

### ISSUE THREAD

**Issue by Hsien-Ming-Ku** [ManuelMBaumann/msKrylov#1]
Dear Baumann,
I am Xian-Ming Gu. Maybe, you still know me. I am greatly interested in test some shifted problems by the nested Krylov solvers (SISC paper) proposed by you and your supervisor. I continued to look at the information of your homepage, it reads "M. Baumann, M. B. van Gijzen (2014). Nested Krylov methods for shifted linear systems. DIAM Technical Report 14-01, TU Delft. ***Code*** (which is a link 'https://bitbucket.org/ManuelMBaumann/nestedkrylov')", but I fail to open this link for many times. So it means that your codes are still unavailable now?

**Comment by ManuelMBaumann** [comment]
Hi,
The code you are looking for is here: https://bitbucket.org/ManuelMBaumann/nestedkrylov
We will close this repository soon.

Best regards,
   Manuel

**Comment by Hsien-Ming-Ku** [comment]
Dear Mr. Manuel,
Thank you very much for sharing your codes with us.  It seems that I am supposed to ask you for help. 
I will add some numerical experiments about comparing your nested solvers with our established solvers. 
All in all, thank you again.
Have a nice day,

Best regards,
Xianming
